// src/Web/src/features/daq/mqtt.tsx
import { useEffect, useState } from 'react'
import { toast } from 'sonner'
import { Button } from '@/components/ui/button'
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card'
import { Input } from '@/components/ui/input'
import { Label } from '@/components/ui/label'
import { canWrite, studioApi, type MqttSinkDocument } from '@/lib/studio-api'
import { useAuthStore } from '@/stores/auth-store'
import { PageShell } from './page-shell'

export function MqttPage() {
  const writable = canWrite(useAuthStore((state) => state.auth.user?.role[0]))
  const [mqtt, setMqtt] = useState<MqttSinkDocument | null>(null)
  const [message, setMessage] = useState('')

  useEffect(() => {
    void studioApi<MqttSinkDocument>('/api/v1/config/sinks/mqtt')
      .then(setMqtt)
      .catch((error: Error) => setMessage(error.message))
  }, [])

  async function save() {
    if (!mqtt) return
    const saved = await studioApi<MqttSinkDocument>('/api/v1/config/sinks/mqtt', {
      method: 'PUT',
      body: JSON.stringify(mqtt),
    })
    setMqtt(saved)
    setMessage('MQTT 已写入草稿')
    toast.success('MQTT 已保存')
  }

  if (!mqtt) {
    return (
      <PageShell title='北向 MQTT'>
        <p className='text-sm text-muted-foreground'>{message || '加载中…'}</p>
      </PageShell>
    )
  }

  const broker = mqtt.spec.broker
  return (
    <PageShell
      title='北向 MQTT'
      description='密码只写环境变量名，不写明文。主题仍是 daq/{site}/{deviceId}/{point}。'
    >
      <Card className='max-w-2xl'>
        <CardHeader>
          <CardTitle>Broker</CardTitle>
        </CardHeader>
        <CardContent className='grid gap-3 sm:grid-cols-2'>
          <Field label='主机'>
            <Input
              value={broker.host}
              disabled={!writable}
              onChange={(event) =>
                setMqtt({ ...mqtt, spec: { ...mqtt.spec, broker: { ...broker, host: event.target.value } } })
              }
            />
          </Field>
          <Field label='端口'>
            <Input
              type='number'
              value={broker.port}
              disabled={!writable}
              onChange={(event) =>
                setMqtt({
                  ...mqtt,
                  spec: { ...mqtt.spec, broker: { ...broker, port: Number(event.target.value) } },
                })
              }
            />
          </Field>
          <Field label='Client ID'>
            <Input
              value={broker.clientId}
              disabled={!writable}
              onChange={(event) =>
                setMqtt({
                  ...mqtt,
                  spec: { ...mqtt.spec, broker: { ...broker, clientId: event.target.value } },
                })
              }
            />
          </Field>
          <Field label='QoS'>
            <Input
              type='number'
              value={mqtt.spec.qos}
              disabled={!writable}
              onChange={(event) =>
                setMqtt({ ...mqtt, spec: { ...mqtt.spec, qos: Number(event.target.value) } })
              }
            />
          </Field>
          <Field label='用户名环境变量'>
            <Input
              value={broker.usernameFromEnv ?? ''}
              disabled={!writable}
              placeholder='MQTT_USER'
              onChange={(event) =>
                setMqtt({
                  ...mqtt,
                  spec: {
                    ...mqtt.spec,
                    broker: { ...broker, usernameFromEnv: event.target.value || null },
                  },
                })
              }
            />
          </Field>
          <Field label='密码环境变量'>
            <Input
              value={broker.passwordFromEnv ?? ''}
              disabled={!writable}
              placeholder='MQTT_PASSWORD'
              onChange={(event) =>
                setMqtt({
                  ...mqtt,
                  spec: {
                    ...mqtt.spec,
                    broker: { ...broker, passwordFromEnv: event.target.value || null },
                  },
                })
              }
            />
          </Field>
          <Field label='点位主题'>
            <Input
              value={mqtt.spec.topicTemplate}
              disabled={!writable}
              onChange={(event) =>
                setMqtt({ ...mqtt, spec: { ...mqtt.spec, topicTemplate: event.target.value } })
              }
            />
          </Field>
          <Field label='状态主题'>
            <Input
              value={mqtt.spec.statusTopic}
              disabled={!writable}
              onChange={(event) =>
                setMqtt({ ...mqtt, spec: { ...mqtt.spec, statusTopic: event.target.value } })
              }
            />
          </Field>
          <div className='sm:col-span-2'>
            <Button disabled={!writable} onClick={() => void save().catch((error: Error) => setMessage(error.message))}>
              保存草稿
            </Button>
            {message ? <p className='mt-2 text-sm text-muted-foreground'>{message}</p> : null}
          </div>
        </CardContent>
      </Card>
    </PageShell>
  )
}

function Field({ label, children }: { label: string; children: React.ReactNode }) {
  return (
    <div className='grid gap-1.5'>
      <Label>{label}</Label>
      {children}
    </div>
  )
}

// studio/web/src/views/Mqtt.vue
<script setup>
import { computed, onMounted, ref } from 'vue'
import { api } from '../api'
import { clone } from '../format'
import { canWrite, refreshWorkspace, workspace } from '../store'

const mqtt = ref(null)
const devices = ref([])
const previewDevice = ref('cnc-01')
const previewPoint = ref('state')
const error = ref('')
const message = ref('')
const pending = ref(false)
const writable = computed(() => canWrite())

onMounted(async () => {
  try {
    mqtt.value = await api('/api/v1/config/sinks/mqtt')
    devices.value = await api('/api/v1/config/devices')
    if (devices.value[0]) previewDevice.value = devices.value[0].metadata.id
  } catch (err) {
    error.value = err.message || '加载 MQTT 配置失败'
  }
})

function fill(template, point) {
  return (template || '')
    .replaceAll('{site}', workspace.siteId || 'site')
    .replaceAll('{deviceId}', previewDevice.value || 'device')
    .replaceAll('{point}', point || 'point')
}

const preview = computed(() => {
  if (!mqtt.value) return { topic: '', status: '', payload: '' }
  const topic = fill(mqtt.value.spec.topicTemplate, previewPoint.value)
  const status = fill(mqtt.value.spec.statusTopic, '')
  const payload = {
    site: workspace.siteId || 'plant-a',
    deviceId: previewDevice.value,
    point: previewPoint.value,
    value: previewPoint.value === 'state' ? 'RUNNING' : '…',
    quality: 'good',
    ts: new Date().toISOString()
  }
  return { topic, status, payload: JSON.stringify(payload, null, 2) }
})

async function save() {
  error.value = ''
  message.value = ''
  pending.value = true
  try {
    const body = clone(mqtt.value)
    body.spec.broker.usernameFromEnv = body.spec.broker.usernameFromEnv || null
    body.spec.broker.passwordFromEnv = body.spec.broker.passwordFromEnv || null
    mqtt.value = await api('/api/v1/config/sinks/mqtt', {
      method: 'PUT',
      body: JSON.stringify(body)
    })
    message.value = 'MQTT 已写入草稿。密码只保存环境变量名，不保存明文。'
    await refreshWorkspace()
  } catch (err) {
    error.value = err.message || '保存失败'
  } finally {
    pending.value = false
  }
}
</script>

<template>
  <main class="page">
    <p v-if="error" class="banner error">{{ error }}</p>
    <p v-if="message" class="banner ok">{{ message }}</p>
    <section v-if="mqtt" class="split">
      <form class="panel stack" @submit.prevent="save">
        <h2>Broker</h2>
        <div class="fields">
          <div class="field">
            <label for="mqtt-id">标识</label>
            <input id="mqtt-id" v-model="mqtt.metadata.id" :disabled="!writable" />
          </div>
          <div class="field">
            <label for="mqtt-host">地址</label>
            <input id="mqtt-host" v-model="mqtt.spec.broker.host" :disabled="!writable" />
          </div>
          <div class="field">
            <label for="mqtt-port">端口</label>
            <input id="mqtt-port" v-model.number="mqtt.spec.broker.port" type="number" :disabled="!writable" />
          </div>
          <div class="field">
            <label for="mqtt-client">Client Id</label>
            <input id="mqtt-client" v-model="mqtt.spec.broker.clientId" :disabled="!writable" />
          </div>
          <div class="field">
            <label for="mqtt-user">用户名环境变量</label>
            <input id="mqtt-user" v-model="mqtt.spec.broker.usernameFromEnv" placeholder="MQTT_USER" :disabled="!writable" />
          </div>
          <div class="field">
            <label for="mqtt-password">密码环境变量</label>
            <input id="mqtt-password" v-model="mqtt.spec.broker.passwordFromEnv" placeholder="MQTT_PASSWORD" :disabled="!writable" />
          </div>
          <div class="field wide">
            <label for="mqtt-topic">主题模板</label>
            <input id="mqtt-topic" v-model="mqtt.spec.topicTemplate" :disabled="!writable" />
          </div>
          <div class="field wide">
            <label for="mqtt-status">状态主题</label>
            <input id="mqtt-status" v-model="mqtt.spec.statusTopic" :disabled="!writable" />
          </div>
          <div class="field">
            <label for="mqtt-qos">QoS</label>
            <select id="mqtt-qos" v-model.number="mqtt.spec.qos" :disabled="!writable">
              <option :value="0">0</option>
              <option :value="1">1</option>
              <option :value="2">2</option>
            </select>
          </div>
          <label class="check">
            <input v-model="mqtt.spec.retain" type="checkbox" :disabled="!writable" />
            Retain
          </label>
        </div>
        <div>
          <button class="btn primary" type="submit" :disabled="!writable || pending">保存草稿</button>
        </div>
      </form>
      <section class="panel stack">
        <h2>JSON 预览</h2>
        <div class="fields">
          <div class="field">
            <label for="preview-device">设备</label>
            <select id="preview-device" v-model="previewDevice">
              <option v-for="device in devices" :key="device.metadata.id" :value="device.metadata.id">{{ device.metadata.id }}</option>
            </select>
          </div>
          <div class="field">
            <label for="preview-point">点位</label>
            <input id="preview-point" v-model="previewPoint" />
          </div>
        </div>
        <div>
          <div class="label">点位主题</div>
          <code>{{ preview.topic }}</code>
        </div>
        <div>
          <div class="label">状态主题</div>
          <code>{{ preview.status }}</code>
        </div>
        <pre class="preview">{{ preview.payload }}</pre>
        <p class="muted">这是页面预览。网关进程实际发布时还会带上 gatewayId、quality 和 ts。</p>
      </section>
    </section>
  </main>
</template>
