// src/Web/src/features/daq/runtime.tsx
import { useEffect, useState } from 'react'
import { Badge } from '@/components/ui/badge'
import {
  Card,
  CardContent,
  CardHeader,
  CardTitle,
} from '@/components/ui/card'
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from '@/components/ui/table'
import { studioApi, type RuntimeStatus } from '@/lib/studio-api'
import { PageShell } from './page-shell'

type Observation = {
  deviceId: string
  point: string
  value?: string | null
  quality: string
  timestamp: string
}

export function RuntimePage() {
  const [status, setStatus] = useState<RuntimeStatus | null>(null)
  const [observations, setObservations] = useState<Observation[]>([])
  const [lines, setLines] = useState<string[]>([])
  const [error, setError] = useState('')

  useEffect(() => {
    let stop = false
    async function load() {
      try {
        const [nextStatus, samples, logs] = await Promise.all([
          studioApi<RuntimeStatus>('/api/v1/runtime/status'),
          studioApi<{ observations: Observation[] }>('/api/v1/runtime/observations?limit=40'),
          studioApi<{ lines: string[] }>('/api/v1/runtime/logs/tail?lines=40'),
        ])
        if (stop) return
        setStatus(nextStatus)
        setObservations(samples.observations)
        setLines(logs.lines)
        setError('')
      } catch (err) {
        if (!stop) setError(err instanceof Error ? err.message : '加载失败')
      }
    }
    void load()
    const timer = window.setInterval(() => void load(), 3000)
    return () => {
      stop = true
      window.clearInterval(timer)
    }
  }, [])

  const live = status?.mode === 'live'

  return (
    <PageShell
      title='运行态'
      description={
        live
          ? '数据来自本进程的采集会话。发布后会立刻重新加载已发布配置。'
          : '采集未启动，当前是模拟数据。用默认方式启动 Host 后会切换为真实状态。'
      }
    >
      {error ? <p className='mb-3 text-sm text-destructive'>{error}</p> : null}
      <div className='mb-4'>
        <Badge variant={live ? 'default' : 'secondary'}>
          {live ? `live · ${(status?.activeRevision || '').slice(0, 12)}` : 'mock'}
        </Badge>
      </div>
      <div className='grid gap-4 xl:grid-cols-2'>
        <Card>
          <CardHeader>
            <CardTitle>设备</CardTitle>
          </CardHeader>
          <CardContent>
            <Table>
              <TableHeader>
                <TableRow>
                  <TableHead>设备</TableHead>
                  <TableHead>适配器</TableHead>
                  <TableHead>状态</TableHead>
                  <TableHead>说明</TableHead>
                </TableRow>
              </TableHeader>
              <TableBody>
                {status?.devices.map((device) => (
                  <TableRow key={device.id}>
                    <TableCell>
                      <div>{device.displayName}</div>
                      <div className='text-xs text-muted-foreground'>{device.id}</div>
                    </TableCell>
                    <TableCell>{device.adapter}</TableCell>
                    <TableCell>{statusLabel(device.status)}</TableCell>
                    <TableCell className='text-xs'>{device.message}</TableCell>
                  </TableRow>
                ))}
              </TableBody>
            </Table>
          </CardContent>
        </Card>
        <Card>
          <CardHeader>
            <CardTitle>最近观测</CardTitle>
          </CardHeader>
          <CardContent className='max-h-80 overflow-auto'>
            <Table>
              <TableHeader>
                <TableRow>
                  <TableHead>设备</TableHead>
                  <TableHead>点位</TableHead>
                  <TableHead>值</TableHead>
                </TableRow>
              </TableHeader>
              <TableBody>
                {observations.map((item, index) => (
                  <TableRow key={`${item.deviceId}-${item.point}-${item.timestamp}-${index}`}>
                    <TableCell>{item.deviceId}</TableCell>
                    <TableCell>{item.point}</TableCell>
                    <TableCell>
                      {item.value} <span className='text-xs text-muted-foreground'>{item.quality}</span>
                    </TableCell>
                  </TableRow>
                ))}
              </TableBody>
            </Table>
          </CardContent>
        </Card>
      </div>
      <Card className='mt-4'>
        <CardHeader>
          <CardTitle>日志</CardTitle>
        </CardHeader>
        <CardContent>
          <pre className='max-h-64 overflow-auto text-xs'>{lines.join('\n') || '暂无日志'}</pre>
        </CardContent>
      </Card>
    </PageShell>
  )
}

function statusLabel(status: string) {
  if (status === 'online') return '在线'
  if (status === 'offline') return '离线'
  if (status === 'disabled') return '禁用'
  if (status === 'degraded') return '降级'
  return status
}

// studio/web/src/views/Runtime.vue
<script setup>
import { onMounted, onUnmounted, ref } from 'vue'
import { api } from '../api'
import { formatTime, shortRev, statusLabel } from '../format'

const status = ref(null)
const observations = ref([])
const lines = ref([])
const deviceId = ref('')
const error = ref('')
let timer = 0

async function load() {
  try {
    const query = deviceId.value ? `?deviceId=${encodeURIComponent(deviceId.value)}&limit=50` : '?limit=50'
    const [runtime, samples, logs] = await Promise.all([
      api('/api/v1/runtime/status'),
      api(`/api/v1/runtime/observations${query}`),
      api('/api/v1/runtime/logs/tail?lines=80')
    ])
    status.value = runtime
    observations.value = samples.observations || []
    lines.value = logs.lines || []
    error.value = ''
  } catch (err) {
    error.value = err.message || '加载运行态失败'
  }
}

onMounted(() => {
  load()
  timer = window.setInterval(load, 3000)
})

onUnmounted(() => window.clearInterval(timer))
</script>

<template>
  <main class="page">
    <p class="banner warn">当前运行态是模拟数据，方便在 Studio 独立运行时看在线状态和最近观测。接入网关进程后可以换成真实状态。</p>
    <p v-if="error" class="banner error">{{ error }}</p>
    <section class="cards">
      <article class="card">
        <div class="label">状态</div>
        <div class="value">{{ statusLabel(status?.state) }}</div>
        <div class="sub">{{ statusLabel(status?.mode) }} · {{ shortRev(status?.activeRevision) }}</div>
      </article>
      <article class="card">
        <div class="label">站点</div>
        <div class="value" style="font-size: 18px">{{ status?.name || '—' }}</div>
        <div class="sub">{{ status?.siteId }}</div>
      </article>
    </section>

    <section class="panel">
      <h2>设备</h2>
      <div class="table-wrap">
        <table>
          <thead>
            <tr>
              <th>设备</th>
              <th>适配器</th>
              <th>状态</th>
              <th>最后见到</th>
              <th>说明</th>
            </tr>
          </thead>
          <tbody>
            <tr v-for="device in status?.devices || []" :key="device.id">
              <td>{{ device.displayName || device.id }} <span class="muted">{{ device.id }}</span></td>
              <td>{{ device.adapter }}</td>
              <td><span class="badge" :class="device.status === 'online' ? 'ok' : device.status === 'offline' ? 'bad' : 'muted'">{{ statusLabel(device.status) }}</span></td>
              <td>{{ formatTime(device.lastSeen) }}</td>
              <td>{{ device.message }}</td>
            </tr>
          </tbody>
        </table>
      </div>
    </section>

    <section class="panel stack">
      <div class="row">
        <h2 style="margin: 0">最近观测</h2>
        <select v-model="deviceId" @change="load">
          <option value="">全部设备</option>
          <option v-for="device in status?.devices || []" :key="device.id" :value="device.id">{{ device.id }}</option>
        </select>
      </div>
      <div class="table-wrap">
        <table>
          <thead>
            <tr>
              <th>设备</th>
              <th>点位</th>
              <th>值</th>
              <th>质量</th>
              <th>时间</th>
            </tr>
          </thead>
          <tbody>
            <tr v-for="row in observations" :key="row.deviceId + row.point">
              <td>{{ row.deviceId }}</td>
              <td>{{ row.point }}</td>
              <td>{{ row.value }}</td>
              <td>{{ row.quality }}</td>
              <td>{{ formatTime(row.timestamp) }}</td>
            </tr>
          </tbody>
        </table>
      </div>
    </section>

    <section class="panel">
      <h2>日志尾部</h2>
      <pre class="log">{{ lines.join('\n') }}</pre>
    </section>
  </main>
</template>
