// studio/web/src/views/Settings.vue
<script setup>
import { computed, onMounted, reactive, ref } from 'vue'
import { api } from '../api'
import { roleLabel } from '../format'
import { canWrite, refreshWorkspace } from '../store'

const form = reactive({
  siteId: '',
  name: '',
  logLevel: 'Information',
  programWrite: false,
  defaultIntervalMs: 1000,
  changeOnly: true
})
const settings = ref(null)
const error = ref('')
const message = ref('')
const pending = ref(false)
const writable = computed(() => canWrite())
const levels = ['Trace', 'Debug', 'Information', 'Warning', 'Error', 'Critical']

async function load() {
  const data = await api('/api/v1/settings')
  settings.value = data
  form.siteId = data.siteId
  form.name = data.name
  form.logLevel = data.logLevel
  form.programWrite = data.programWrite
  form.defaultIntervalMs = data.defaultIntervalMs
  form.changeOnly = data.changeOnly
}

onMounted(async () => {
  try {
    await load()
  } catch (err) {
    error.value = err.message || '加载系统设置失败'
  }
})

async function save() {
  error.value = ''
  message.value = ''
  pending.value = true
  try {
    await api('/api/v1/settings', {
      method: 'PUT',
      body: JSON.stringify(form)
    })
    message.value = '站点设置已写入草稿，发布后才会生效。'
    await load()
    await refreshWorkspace()
  } catch (err) {
    error.value = err.message || '保存失败'
  } finally {
    pending.value = false
  }
}
</script>

<template>
  <main class="page">
    <p v-if="error" class="banner error">{{ error }}</p>
    <p v-if="message" class="banner ok">{{ message }}</p>
    <section class="panel stack">
      <h2>站点</h2>
      <div class="fields">
        <div class="field">
          <label for="site-id">站点标识</label>
          <input id="site-id" v-model="form.siteId" :disabled="!writable" />
        </div>
        <div class="field">
          <label for="site-name">站点名称</label>
          <input id="site-name" v-model="form.name" :disabled="!writable" />
        </div>
        <div class="field">
          <label for="log-level">日志级别</label>
          <select id="log-level" v-model="form.logLevel" :disabled="!writable">
            <option v-for="level in levels" :key="level" :value="level">{{ level }}</option>
          </select>
        </div>
        <div class="field">
          <label for="interval">默认采集周期（毫秒）</label>
          <input id="interval" v-model.number="form.defaultIntervalMs" type="number" min="100" :disabled="!writable" />
        </div>
        <label class="check">
          <input v-model="form.changeOnly" type="checkbox" :disabled="!writable" />
          仅在点位变化时上传
        </label>
        <label class="check">
          <input v-model="form.programWrite" type="checkbox" :disabled="!writable" />
          允许程序写入（未实现，建议关闭）
        </label>
      </div>
      <div>
        <button class="btn primary" type="button" :disabled="!writable || pending" @click="save">保存草稿</button>
      </div>
      <p v-if="settings" class="muted">配置目录：<code>{{ settings.dataDirectory }}</code></p>
    </section>

    <section v-if="settings" class="panel">
      <h2>许可证</h2>
      <p><span class="badge">{{ settings.license.status }}</span> {{ settings.license.edition }}</p>
      <p>{{ settings.license.message }}</p>
    </section>

    <section class="panel">
      <h2>用户</h2>
      <p class="muted">当前用户 {{ settings?.currentUser?.username }}（{{ roleLabel(settings?.currentUser?.role) }}）。M1 是本地单机账号，不提供在线改密。</p>
      <table v-if="settings?.users?.length">
        <thead>
          <tr>
            <th>用户名</th>
            <th>角色</th>
          </tr>
        </thead>
        <tbody>
          <tr v-for="user in settings.users" :key="user.username">
            <td>{{ user.username }}</td>
            <td>{{ roleLabel(user.role) }}</td>
          </tr>
        </tbody>
      </table>
    </section>
  </main>
</template>

// src/Web/src/features/daq/settings.tsx
import { useEffect, useState } from 'react'
import { toast } from 'sonner'
import { Button } from '@/components/ui/button'
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card'
import { Input } from '@/components/ui/input'
import { Label } from '@/components/ui/label'
import { Switch } from '@/components/ui/switch'
import { canWrite, roleLabel, studioApi } from '@/lib/studio-api'
import { useAuthStore } from '@/stores/auth-store'
import { PageShell } from './page-shell'

type SettingsView = {
  siteId: string
  name: string
  logLevel: string
  programWrite: boolean
  defaultIntervalMs: number
  changeOnly: boolean
  dataDirectory: string
  license: { enforced: boolean; message: string }
  currentUser: { username: string; role: string }
  users: Array<{ username: string; role: string }>
}

export function SettingsPage() {
  const writable = canWrite(useAuthStore((state) => state.auth.user?.role[0]))
  const [settings, setSettings] = useState<SettingsView | null>(null)
  const [message, setMessage] = useState('')

  useEffect(() => {
    void studioApi<SettingsView>('/api/v1/settings')
      .then(setSettings)
      .catch((error: Error) => setMessage(error.message))
  }, [])

  async function save() {
    if (!settings) return
    await studioApi('/api/v1/settings', {
      method: 'PUT',
      body: JSON.stringify({
        siteId: settings.siteId,
        name: settings.name,
        logLevel: settings.logLevel,
        programWrite: settings.programWrite,
        defaultIntervalMs: settings.defaultIntervalMs,
        changeOnly: settings.changeOnly,
      }),
    })
    setMessage('已写入网关草稿，发布后才会影响运行中的主题')
    toast.success('系统设置已保存到草稿')
  }

  if (!settings) {
    return (
      <PageShell title='系统'>
        <p className='text-sm text-muted-foreground'>{message || '加载中…'}</p>
      </PageShell>
    )
  }

  return (
    <PageShell title='系统' description='站点名写入 Gateway 草稿。许可证桩当前不拦截管理 API。'>
      <div className='grid gap-4 lg:grid-cols-2'>
        <Card>
          <CardHeader>
            <CardTitle>站点</CardTitle>
          </CardHeader>
          <CardContent className='grid gap-3'>
            <Field label='站点 id'>
              <Input
                value={settings.siteId}
                disabled={!writable}
                onChange={(event) => setSettings({ ...settings, siteId: event.target.value })}
              />
            </Field>
            <Field label='名称'>
              <Input
                value={settings.name}
                disabled={!writable}
                onChange={(event) => setSettings({ ...settings, name: event.target.value })}
              />
            </Field>
            <Field label='默认扫描周期 ms'>
              <Input
                type='number'
                value={settings.defaultIntervalMs}
                disabled={!writable}
                onChange={(event) =>
                  setSettings({ ...settings, defaultIntervalMs: Number(event.target.value) })
                }
              />
            </Field>
            <div className='flex items-center justify-between'>
              <Label>仅变化时发布</Label>
              <Switch
                checked={settings.changeOnly}
                disabled={!writable}
                onCheckedChange={(changeOnly) => setSettings({ ...settings, changeOnly })}
              />
            </div>
            <Button disabled={!writable} onClick={() => void save().catch((error: Error) => setMessage(error.message))}>
              保存草稿
            </Button>
            {message ? <p className='text-sm text-muted-foreground'>{message}</p> : null}
          </CardContent>
        </Card>
        <Card>
          <CardHeader>
            <CardTitle>账号与许可证</CardTitle>
          </CardHeader>
          <CardContent className='space-y-2 text-sm'>
            <p>
              当前用户：{settings.currentUser.username} · {roleLabel(settings.currentUser.role)}
            </p>
            <p>数据目录：{settings.dataDirectory}</p>
            <p>{settings.license.message}</p>
            {settings.users.length > 0 ? (
              <ul>
                {settings.users.map((user) => (
                  <li key={user.username}>
                    {user.username} · {roleLabel(user.role)}
                  </li>
                ))}
              </ul>
            ) : null}
          </CardContent>
        </Card>
      </div>
    </PageShell>
  )
}

function Field({ label, children }: { label: string; children: React.ReactNode }) {
  return (
    <div className='grid gap-1.5'>
      <Label>{label}</Label>
      {children}
    </div>
  )
}
